In [1]:
import matplotlib.pyplot as plt
import numpy as np
import os

In [2]:
input_folder = "Z:/LeoF/Cygnus/Files"
trial = "p3_1.set_frequent_frequent_electrodes.npy"
# have to sum across electrodes and pip types I think 

# input_path = os.path.join(input_folder, trial)

trial_freq = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_freq.npy", allow_pickle = True)
trial_power = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_power.npy",  allow_pickle = True)

In [ ]:
trial_power.shape

# --- Shape of trial_power ---
# 1st dimension electrodes (28)
# 2nd dimension data types (1. pre, 2. post, 3. post_minus_erp, 4. fft_erp) (4)
# 3rd dimension epochs (154)

(28, 4, 154)

In [28]:
# model 1 -- do I average across electrodes for the models? -- I think so for the visualizaiton
pre_event_spectra = trial_power[:,0,:] # Pre-event spectra indexing 
post_event_spectra = trial_power[:,1,:] # Post-event spectra indexing

residual_power_model_1 = post_event_spectra - pre_event_spectra
pre_event_spectra.shape


(28, 154)

In [32]:
# trial_freq = trial_freq.item()
xf_pre = trial_freq['xf_pre']
xf_post = trial_freq['xf_post']

#mask for the pre an post frequencies (I have to seperate them )
# can look at frequencies > 3hz because of cropping window and filtering out above 26
# xf_pre = xf_pre[(xf_pre > 3) & (xf_pre < 26)]
# xf_pre


print(len(xf_pre))
print(xf_pre.shape)
print(len(pre_event_spectra))
print(pre_event_spectra.shape)

154
(154,)
28
(28, 154)


In [16]:
xf_pre

array([   0.        ,    1.66233766,    3.32467532,    4.98701299,
          6.64935065,    8.31168831,    9.97402597,   11.63636364,
         13.2987013 ,   14.96103896,   16.62337662,   18.28571429,
         19.94805195,   21.61038961,   23.27272727,   24.93506494,
         26.5974026 ,   28.25974026,   29.92207792,   31.58441558,
         33.24675325,   34.90909091,   36.57142857,   38.23376623,
         39.8961039 ,   41.55844156,   43.22077922,   44.88311688,
         46.54545455,   48.20779221,   49.87012987,   51.53246753,
         53.19480519,   54.85714286,   56.51948052,   58.18181818,
         59.84415584,   61.50649351,   63.16883117,   64.83116883,
         66.49350649,   68.15584416,   69.81818182,   71.48051948,
         73.14285714,   74.80519481,   76.46753247,   78.12987013,
         79.79220779,   81.45454545,   83.11688312,   84.77922078,
         86.44155844,   88.1038961 ,   89.76623377,   91.42857143,
         93.09090909,   94.75324675,   96.41558442,   98.07792

In [5]:
trial_power.shape

(28, 4, 154)

In [6]:
pre_event_spectra

array([[5.49215812e-38, 1.24912933e-06, 2.97026704e-07, ...,
        1.42403224e-07, 2.97026704e-07, 1.24912933e-06],
       [1.09351128e-38, 2.66525106e-07, 8.44104536e-08, ...,
        6.47054850e-08, 8.44104536e-08, 2.66525106e-07],
       [2.36444314e-38, 2.51122583e-07, 7.55266924e-08, ...,
        5.01263109e-08, 7.55266924e-08, 2.51122583e-07],
       ...,
       [2.38171258e-38, 2.54787576e-07, 1.09679631e-07, ...,
        6.59007146e-08, 1.09679631e-07, 2.54787576e-07],
       [2.53973279e-38, 1.88733110e-07, 8.64709947e-08, ...,
        6.73436339e-08, 8.64709947e-08, 1.88733110e-07],
       [9.88127002e-39, 8.60736605e-08, 4.28867690e-08, ...,
        3.34616058e-08, 4.28867690e-08, 8.60736605e-08]])

In [7]:
# Why is the first value so small -- did I make a data preprocessing error?
# Are values of 10^-11 too small for eeg?
# why for the residual plots do they have y axis values of 0,1,2,3,4
# they squared the residuals? -- summed across electodes, particpants, and frequencies?


In [8]:
# average across electrodes
np.sum(residual_power_model_1, axis = 0)

array([ 5.31769180e-05,  2.56358523e-06,  5.85316782e-07,  2.17368129e-07,
       -3.90149642e-07, -1.48856197e-06, -7.95920281e-06, -1.40824343e-06,
       -4.15689296e-08,  2.70346224e-08, -5.10579070e-08, -1.07468213e-07,
       -5.58486887e-07, -3.52009337e-07, -2.78116000e-08, -1.63955445e-07,
       -6.13732330e-09, -5.45568337e-08, -2.74831497e-08, -1.97277929e-07,
       -1.60415169e-07, -2.49026181e-07, -7.35747696e-08, -2.81779607e-07,
       -2.88816747e-07, -6.02842408e-08,  2.63191277e-07, -1.40323912e-07,
       -4.94877038e-07, -4.41706685e-08, -1.34897065e-07, -4.10819870e-08,
        2.57263553e-08, -1.51308012e-07,  5.69174583e-08, -6.62628464e-07,
        2.32801495e-07,  1.89864597e-07,  8.77489310e-09, -1.40292629e-07,
       -9.57982321e-08, -1.28727077e-07, -2.21720772e-07, -9.70323024e-08,
        7.89375105e-08, -1.17539757e-07,  8.62882097e-08, -8.88196811e-08,
        4.12204648e-08, -8.99946615e-08, -9.43494573e-08, -1.54112135e-08,
       -1.01244541e-07, -

In [9]:
# Trial_npy are arrays containing dictionaries
# No brackets "[]"
# Trial_npy.ndim will give 0 bcs. no brackets
# Use .item() when working w. 0-dim array
trial_dict = trial_freq.item()

len(trial_dict['xf_pre'])

# How is it possible that I am saving out frequencies at 0? 
# Xf pre and post have a freq value at 0 

AttributeError: 'dict' object has no attribute 'item'

In [ ]:
print(len(trial_dict['Xf_pre']))
print(len(trial_dict['Xf_post']))

KeyError: 'Xf_pre'