In [24]:
import matplotlib.pyplot as plt
from fooof.sim.gen import gen_power_spectrum
import numpy as np
import os

C:\Users\leofl\AppData\Local\Temp\ipykernel_18312\3747758445.py:2: DeprecationWarning: 
The `fooof` package is being deprecated and replaced by the `specparam` (spectral parameterization) package.
This version of `fooof` (1.1) is fully functional, but will not be further updated.
New projects are recommended to update to using `specparam` (see Changelog for details).
  from fooof.sim.gen import gen_power_spectrum


In [2]:
input_folder = "Z:/LeoF/Cygnus/Files"
trial = "p3_1.set_frequent_frequent_electrodes.npy"
# have to sum across electrodes and pip types I think 

# input_path = os.path.join(input_folder, trial)

trial_freq = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_freq.npy", allow_pickle = True)
trial_power = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_power.npy",  allow_pickle = True)

<>:7: SyntaxWarning: invalid escape sequence '\L'
<>:8: SyntaxWarning: invalid escape sequence '\L'
<>:7: SyntaxWarning: invalid escape sequence '\L'
<>:8: SyntaxWarning: invalid escape sequence '\L'
C:\Users\leofl\AppData\Local\Temp\ipykernel_18312\896968058.py:7: SyntaxWarning: invalid escape sequence '\L'
  trial_freq = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_freq.npy", allow_pickle = True)
C:\Users\leofl\AppData\Local\Temp\ipykernel_18312\896968058.py:8: SyntaxWarning: invalid escape sequence '\L'
  trial_power = np.load("Z:\LeoF\Cygnus\Files\p3_1.set_frequent_frequent_power.npy",  allow_pickle = True)


In [3]:
trial_power.shape

# --- Shape of trial_power ---
# 1st dimension electrodes (28)
# 2nd dimension data types (1. pre, 2. post, 3. post_minus_erp, 4. fft_erp) (4)
# 3rd dimension epochs (154)

(28, 4, 154)

In [4]:
# model 1 -- do I average across electrodes for the models? -- I think so for the visualizaiton
pre_event_spectra = trial_power[:,0,:] # Pre-event spectra indexing 
post_event_spectra = trial_power[:,1,:] # Post-event spectra indexing

residual_power_model_1 = post_event_spectra - pre_event_spectra
pre_event_spectra.shape


(28, 154)

In [5]:
trial_freq = trial_freq.item()
xf_pre = trial_freq['xf_pre']
xf_post = trial_freq['xf_post']

#mask for the pre an post frequencies (I have to seperate them )
# can look at frequencies > 3hz because of cropping window and filtering out above 26
# xf_pre = xf_pre[(xf_pre > 3) & (xf_pre < 26)]
# xf_pre


print(len(xf_pre))
print(xf_pre.shape)
print(len(pre_event_spectra))
print(pre_event_spectra.shape)

154
(154,)
28
(28, 154)


In [6]:
xf_pre

array([   0.        ,    1.66233766,    3.32467532,    4.98701299,
          6.64935065,    8.31168831,    9.97402597,   11.63636364,
         13.2987013 ,   14.96103896,   16.62337662,   18.28571429,
         19.94805195,   21.61038961,   23.27272727,   24.93506494,
         26.5974026 ,   28.25974026,   29.92207792,   31.58441558,
         33.24675325,   34.90909091,   36.57142857,   38.23376623,
         39.8961039 ,   41.55844156,   43.22077922,   44.88311688,
         46.54545455,   48.20779221,   49.87012987,   51.53246753,
         53.19480519,   54.85714286,   56.51948052,   58.18181818,
         59.84415584,   61.50649351,   63.16883117,   64.83116883,
         66.49350649,   68.15584416,   69.81818182,   71.48051948,
         73.14285714,   74.80519481,   76.46753247,   78.12987013,
         79.79220779,   81.45454545,   83.11688312,   84.77922078,
         86.44155844,   88.1038961 ,   89.76623377,   91.42857143,
         93.09090909,   94.75324675,   96.41558442,   98.07792

In [7]:
trial_power.shape

(28, 4, 154)

In [8]:
pre_event_spectra

array([[5.49215812e-38, 1.24912933e-06, 2.97026704e-07, ...,
        1.42403224e-07, 2.97026704e-07, 1.24912933e-06],
       [1.09351128e-38, 2.66525106e-07, 8.44104536e-08, ...,
        6.47054850e-08, 8.44104536e-08, 2.66525106e-07],
       [2.36444314e-38, 2.51122583e-07, 7.55266924e-08, ...,
        5.01263109e-08, 7.55266924e-08, 2.51122583e-07],
       ...,
       [2.38171258e-38, 2.54787576e-07, 1.09679631e-07, ...,
        6.59007146e-08, 1.09679631e-07, 2.54787576e-07],
       [2.53973279e-38, 1.88733110e-07, 8.64709947e-08, ...,
        6.73436339e-08, 8.64709947e-08, 1.88733110e-07],
       [9.88127002e-39, 8.60736605e-08, 4.28867690e-08, ...,
        3.34616058e-08, 4.28867690e-08, 8.60736605e-08]])

In [9]:
# Why is the first value so small -- did I make a data preprocessing error?
# Are values of 10^-11 too small for eeg?
# why for the residual plots do they have y axis values of 0,1,2,3,4
# they squared the residuals? -- summed across electodes, particpants, and frequencies?


In [10]:
# average across electrodes
np.sum(residual_power_model_1, axis = 0)

array([ 5.31769180e-05,  2.56358523e-06,  5.85316782e-07,  2.17368129e-07,
       -3.90149642e-07, -1.48856197e-06, -7.95920281e-06, -1.40824343e-06,
       -4.15689296e-08,  2.70346224e-08, -5.10579070e-08, -1.07468213e-07,
       -5.58486887e-07, -3.52009337e-07, -2.78116000e-08, -1.63955445e-07,
       -6.13732330e-09, -5.45568337e-08, -2.74831497e-08, -1.97277929e-07,
       -1.60415169e-07, -2.49026181e-07, -7.35747696e-08, -2.81779607e-07,
       -2.88816747e-07, -6.02842408e-08,  2.63191277e-07, -1.40323912e-07,
       -4.94877038e-07, -4.41706685e-08, -1.34897065e-07, -4.10819870e-08,
        2.57263553e-08, -1.51308012e-07,  5.69174583e-08, -6.62628464e-07,
        2.32801495e-07,  1.89864597e-07,  8.77489310e-09, -1.40292629e-07,
       -9.57982321e-08, -1.28727077e-07, -2.21720772e-07, -9.70323024e-08,
        7.89375105e-08, -1.17539757e-07,  8.62882097e-08, -8.88196811e-08,
        4.12204648e-08, -8.99946615e-08, -9.43494573e-08, -1.54112135e-08,
       -1.01244541e-07, -

In [11]:
# Trial_npy are arrays containing dictionaries
# No brackets "[]"
# Trial_npy.ndim will give 0 bcs. no brackets
# Use .item() when working w. 0-dim array
trial_dict = trial_freq.item()

len(trial_dict['xf_pre'])

# How is it possible that I am saving out frequencies at 0? 
# Xf pre and post have a freq value at 0 

AttributeError: 'dict' object has no attribute 'item'

In [ ]:
print(len(trial_dict['Xf_pre']))
print(len(trial_dict['Xf_post']))

KeyError: 'Xf_pre'

In [ ]:
txt = "Hello, welcome to my world."

x = txt.endswith(".")

print(x)


True


In [ ]:
x = "Z:\LeoF\Cygnus\Files\p3_20.set_rare_frequent_power.npy"
x.endswith("power.npy")

True

In [14]:
# simulate post event power spectrum 
# need a simulate 1/f exponent shift spetrump


# so N is 154
# Fs is 256
freq_resolution = 256 / trial_power.shape[2]

# now we need delta offset and exponent -- differences between post and pre

# where do I get the difference values for exponent and offest
import pandas as pd
exps = pd.read_csv('z:/LeoF/Cygnus/DataFrame/data_frame.csv')

exps_pre = exps[exps['Time Window'] == 'yf_avg_pre'] # Pre exps
exps_post = exps[exps['Time Window'] == 'yf_avg_post'] # Post exps

exps_pre = exps_pre.sort_values(by=['Participant', 'Electrode', 'Condition']).reset_index()
exps_post = exps_post.sort_values(by=['Participant', 'Electrode', 'Condition']).reset_index()

compared = exps_pre[['Participant', 'Electrode', 'Condition']].compare(other = exps_post[['Participant', 'Electrode', 'Condition']], keep_equal=False) 
print(compared) # Ensuring no mismatches
assert compared.empty == True # Should be empty if no mismatches

exps_post['post_minus_pre_Exponent'] = (exps_post['Exponent'] - exps_pre['Exponent']) # Compute post-pre differences
exps_post['post_minus_pre_Offset'] = (exps_post['Offset'] - exps_pre['Offset'])

exps_post

Empty DataFrame
Columns: []
Index: []


index  Unnamed: 0 Participant Electrode          Condition  Time Window  \
0       181         181        p3_1        C3  frequent_frequent  yf_avg_post   
1        13          13        p3_1        C3      frequent_rare  yf_avg_post   
2        97          97        p3_1        C3      rare_frequent  yf_avg_post   
3       232         232        p3_1        C4  frequent_frequent  yf_avg_post   
4        64          64        p3_1        C4      frequent_rare  yf_avg_post   
...     ...         ...         ...       ...                ...          ...   
1675   4864        4864        p3_9       PO8      frequent_rare  yf_avg_post   
1676   4948        4948        p3_9       PO8      rare_frequent  yf_avg_post   
1677   4993        4993        p3_9        Pz  frequent_frequent  yf_avg_post   
1678   4825        4825        p3_9        Pz      frequent_rare  yf_avg_post   
1679   4909        4909        p3_9        Pz      rare_frequent  yf_avg_post   

      Exponent    Offset       Rsq  post_minus_pre_Exponent  \
0     1.187439 -6.311319  0.978670                 0.375094   
1     1.157423 -6.348588  0.957891                 0.122881   
2     1.163947 -6.372938  0.959640                 0.557072   
3     1.016592 -6.440030  0.989732                 0.281460   
4     1.008025 -6.463766  0.940086                 0.265782   
...        ...       ...       ...                      ...   
1675  1.850764 -4.475603  0.983385                 0.239165   
1676  1.839327 -4.332317  0.986105                 0.040790   
1677  1.684097 -5.310160  0.983900                 0.150405   
1678  1.778645 -5.167877  0.987705                 0.166799   
1679  1.788748 -5.066744  0.976626                 0.034314   

      post_minus_pre_Offset  
0                  0.357966  
1                  0.075520  
2                  0.576617  
3                  0.277301  
4                  0.274565  
...                     ...  
1675               0.415483  
1676              -0.115369  
1677               0.198742  
1678               0.234768  
1679              -0.107349  

[1680 rows x 11 columns]

In [31]:
exps = pd.read_csv('z:/LeoF/Cygnus/DataFrame/data_frame.csv')

exps_pre = exps[exps['Time Window'] == 'yf_avg_pre'] # Pre exps
exps_post = exps[exps['Time Window'] == 'yf_avg_post'] # Post exps

exps_pre = exps_pre.sort_values(by=['Participant', 'Electrode', 'Condition']).reset_index()
exps_post = exps_post.sort_values(by=['Participant', 'Electrode', 'Condition']).reset_index()

compared = exps_pre[['Participant', 'Electrode', 'Condition']].compare(other = exps_post[['Participant', 'Electrode', 'Condition']], keep_equal=False) 
assert compared.empty == True # Should be empty if no mismatches

exps_post['post_minus_pre_Exponent'] = (exps_post['Exponent'] - exps_pre['Exponent']) # Compute post-pre differences
exps_post['post_minus_pre_Offset'] = (exps_post['Offset'] - exps_pre['Offset'])

condition_averages = exps_post.groupby(['Participant','Condition']).mean(['post_minus_pre_Exponent','post_minus_pre_Offset']).reset_index()
participant = 'p3_1'
condition = "frequent_frequent"
participant_condition = condition_averages[(condition_averages['Participant'] == participant) & (condition_averages["Condition"] == condition)]
delta_exponent = participant_condition['post_minus_pre_Exponent']
delta_offset = participant_condition['post_minus_pre_Offset']
aperiodic_params = [delta_offset, delta_exponent]    


In [42]:
float(delta_exponent)

C:\Users\leofl\AppData\Local\Temp\ipykernel_18312\3906199707.py:1: FutureWarning: Calling float on a single element Series is deprecated and will raise a TypeError in the future. Use float(ser.iloc[0]) instead
  float(delta_exponent)


0.2762439787724541

In [ ]:
from fooof.sim.gen import gen_power_spectrum

sim_freqs, sim_power = gen_power_spectrum(
    freqs=xf_pre,
    aperiodic_params=aperiodic_params,
    periodic_params=[],
    nlv=0,
    freq_res=1.66  # or whatever you calculated
)

In [25]:
# question now is how do I get the exponent differences 
# the thing with the dataframe is that it has delta exponent and offset by electrode -- but for our visualiztions we are not doing that


freq_resolution

1.6623376623376624